version: "3.8"
services:
  postgres:
    container_name: postgres-phraseplay-db
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:14
    ports:
      - "5465:5432"
    restart: always
    volumes:
      - postgres_phraseplay_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

  postgres-test-db:
    container_name: postgres-phraseplay-test-db
    image: postgres:14
    ports:
      - "5466:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_phraseplay_data:
