import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";
// import { api } from "~/utils/api";
import LogoImage from "../components/assets/logo.svg";
import HomeFeature from "~/features/HomeFeature";
import Image from "next/image";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>PhrasePlay: Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-start bg-blue-500 p-2">
        <div className="flex flex-col items-center justify-center p-2 text-center">
          <Link
            href="/"
            className="title-font mb-4 flex flex-col items-center font-medium text-gray-900 md:mb-0"
          >
            <Image
              className="h-20 w-20 rounded-md bg-white/30 p-3"
              src={LogoImage as string}
              alt="PhrasePlay Logo"
            />
            <h1 className="text-white text-2xl font-light">PhrasePlay</h1>
          </Link>
        </div>
        <main className="container mx-auto max-w-sm rounded-md sm:max-w-md md:max-w-lg lg:max-w-4xl lg:py-8 xl:max-w-5xl 2xl:max-w-6xl">
          <HomeFeature />
        </main>
      </div>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage.secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
